/* w0 scale analysis code
 *
 * Written by Szabolcs Borsanyi
 * borsanyi@uni-wuppertal.de
 * for the Budapest-Marseille-Wuppertal collaboration
 * 14th February 2012
 *
 * This program prints 
 *
 * You can ask for help with the -h option in the command line.
 * 
 * Build instructions:
 *
 * (e.g. gnu C compiler)
 * cc w0_scale.c -o w0_scale -lm
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <err.h>

enum { max_line_len=128 }; /* in the input file */
double Scale_in_fermi;
int Opt_f,Opt_j;
char Opt_o[max_line_len];
double Cut_value=0.3;
char Flow_line_format[256]="WFLOW %lf %lf %lf";
int Nline;
double T_max;
double *T_array; /* each file must have the same time time values
		    for a given line. Here we store what we read
		    from the first file. */

void help()/*{{{*/
{
  puts("w0_scale (by the Budapest-Marseille-Wuppertal collaboration)");
  puts("----------------------------------------------------------------");
  puts("Usage:");
  puts("       w0_scale [options] flow_files.*");
  puts("");
  puts("This program calculates the w0 scale from the flow files");
  puts("generated by our reference implementation in CHROMA or the");
  puts("wilson_flow.c that accompanies this program.");
  puts("The flows corresponding to the configurations may be given");
  puts("as one big concatenated file, or several such files,");
  puts("or even one flow file per configuration.");
  puts("");
  puts("Input line format: WFLOW <flow_time> <Et> <Ex>");
  puts("(further columns after 'WFLOW' are simply ignored).");
  puts("You can change what we expect as first word with the opiton -s");
  puts("The program performs a jackknife error analysis and gives");
  puts("the w0 scale for all samples in the following format:");
  puts("  if you give the -j <n> option: ");
  puts("<w0> <error> <jackknife-1> <jackknife-2> ... <jackknife-n>");
  puts("  or if you don't");
  puts("<w0> <error>");
  puts("");
  puts(" The jackknife method makes <n> blocks and assumes that the");
  puts("configurations are correctly ordered (as in the HMC/update stream");
  puts("In principle, you can use as many blocks as configurations.");
  puts("It is your responsibility to keep the block size larger than");
  puts("the autocorrelation time.");
  puts("You can even evaluate one flow file based on a single configuration,");
  puts("where you get a nan or nonsense for the error estimate. In that case");
  puts("You might be interested in comparing what you get for the spatial");
  puts("and tempral directions, separately with  -x or -t"); 
  puts("");
  puts("Options:");
  puts("         -c<cut>  Use a cut value other than 0.3");
  puts("         -o<file_name>");
  puts("                  Write the measured field stregth as a");
  puts("                  function of the flow time. Format:");
  puts("                  <t> <t^2E> <error> <t d (t^2 E) / dt> <error>");
  puts("                      <t^2 d^2 (t^2 E) / dt^2> <error>");
  puts("         -x       Use the spatial field strength only");
  puts("         -t       Use the temporal field strength only");
  puts("         -j<n>");
  puts("                  Number of jack-knife samples (default=20)");
  puts("         -f       Tell the lattice spacing in fermi if possible");
  puts("         -s<label> The 1st word that identifies a flow line");
  puts("");
  puts("Questions? Ask borsanyi@uni-wuppertal.de");
}/*}}}*/

/* CSPLINE {{{ */

/* This block of code is a general purpose cubic spline calculator 
 * Not all are relevant for the w0 scale calculator, but it is 
 * perhaps better not to disintegrate the package.
 * */

/* The basic interface:
 *
 * struct cspline my_spline;        you need such kind of a variable,
 *                                  and pass its address &my_spline to
 *                                  the routines below.
 *
 * int cspline_init(struct cspline *C,double *xin,double *yin,int n);
 *      It initializes the spline (allocate more memory, calculate
 *      the coefficients, etc).
 *      xin is the X data, yin is the array of Y data, with n numbers each.
 *      The input array xin must be sorted. (In either way.)
 *      It returns 0 on success.
 *
 * void cspline_destroy(struct cspline *C);
 *      free the allocated memory. Two consecutive destroys, are safe,
 *      destroying an unititialized object is not.
 *
 * int cspline_is_initialized(struct cspline *C);
 *      It may be called only if the spline has already been initialized,
 *      but possibly later destroyed.
 *      It returns 1 if C is initialized, 0 if not.
 *
 * The following functions must be called with an initialized spline.
 *
 * double cspline_val(const struct cspline *C,double x);
 *      The spline interpolation at x.
 *      You get 'inf' when x is out of range.
 *
 * double cspline_derive(const struct cspline *C,double x);
 *      The derivative of the spline interpolation at x.
 *      You get 'inf' when x is out of range.
 *
 * double cspline_derive2(const struct cspline *C,double x);
 *      The 2nd derivative of the spline interpolation at x.
 *      You get 'inf' when x is out of range.
 *
 * double cspline_integrate(const struct cspline *C,double x)
 *      The integral of the interpolation from the smallest xin value to x.
 *      Again, you get 'inf' when x is out of range.
 *
 * double cspline_integrate_r(const struct cspline *C,double x)
 *      The integral of the interpolation from x to the largest xin value.
 *      Again, you get 'inf' when x is out of range.
 *
 * double cspline_integrate_full(const struct cspline *C)
 *      The integral of the interpolation from the smallest
 *      to the largest xin value.
 *
 */
#include <stdlib.h>
#include <math.h>
#include <float.h>
struct cspline {/*{{{*/
  const double *x; /* x data points, sorted */
  double (*c)[4]; /* coefficients */
  int n; /* number of data points */
};/*}}}*/

double cspline_integrate_full(const struct cspline *C)/*{{{*/
  /* integrate the full range of the spline */
{
#define primfn(l,x) (C->c[l][0]*x+C->c[l][1]*x*x/2.+C->c[l][2]*x*x*x/3.+C->c[l][3]*x*x*x*x/4.)
#define integral(l) (primfn(l,b[l+1])-primfn(l,b[l]))
  int i,r=C->n-1;
  const double *b=C->x;
  double s=0;
  for(i=0;i<r;i++) s+=integral(i);
  return s;
#undef integral
#undef primfn
}/*}}}*/

double cspline_integrate(const struct cspline *C,double x)/*{{{*/
  /* integrate from initial point to x */
{
#define in_range(x,left,right) ((b[left]-x)*(x-b[right])>-DBL_EPSILON) 
#define primfn(l,x) (C->c[l][0]*x+C->c[l][1]*x*x/2.+C->c[l][2]*x*x*x/3.+C->c[l][3]*x*x*x*x/4.)
#define integral(l) (primfn(l,b[l+1])-primfn(l,b[l]))
  int i,r=C->n-1;
  const double *b=C->x;
  double s=0;
  if(!in_range(x,0,r)) return HUGE_VAL;
  for(i=0;i<r;i++) {
    if(in_range(x,i,i+1)) {
      s+=primfn(i,x)-primfn(i,b[i]);
      break;
    } else {
      s+=integral(i);
    }
  }
  return s;
#undef integral
#undef primfn
#undef in_range
}/*}}}*/

double cspline_integrate_r(const struct cspline *C,double x)/*{{{*/
  /* integrate from x to the final point */
{
#define in_range(x,left,right) ((b[left]-x)*(x-b[right])>-DBL_EPSILON) 
#define primfn(l,x) (C->c[l][0]*x+C->c[l][1]*x*x/2.+C->c[l][2]*x*x*x/3.+C->c[l][3]*x*x*x*x/4.)
#define integral(l) (primfn(l,b[l+1])-primfn(l,b[l]))
  int i,r=C->n-1;
  const double *b=C->x;
  double s=0;
  if(!in_range(x,0,r)) return HUGE_VAL;
  for(i=r-1;i>=0;i--) {
    if(in_range(x,i,i+1)) {
      s+=primfn(i,b[i+1])-primfn(i,x);
      break;
    } else {
      s+=integral(i);
    }
  }
  return s;
#undef integral
#undef primfn
#undef in_range
}/*}}}*/

double cspline_derive(const struct cspline *C,double x)/*{{{*/
{
#define in_range(x,left,right) ((b[left]-x)*(x-b[right])>-DBL_EPSILON) 
  int m,l=0,r=C->n-1;
  const double *b=C->x;
  /* search interpolating interval */
  if(!in_range(x,l,r)) return HUGE_VAL;
  while(l+1<r) {
    m=(l+r)/2;
    if(in_range(x,m,r)) l=m; else r=m;
  }
  /* use polynomial */
  return C->c[l][1]+C->c[l][2]*x*2.+C->c[l][3]*x*x*3.;
#undef in_range
}/*}}}*/

double cspline_derive2(const struct cspline *C,double x)/*{{{*/
{
#define in_range(x,left,right) ((b[left]-x)*(x-b[right])>-DBL_EPSILON) 
  int m,l=0,r=C->n-1;
  const double *b=C->x;
  /* search interpolating interval */
  if(!in_range(x,l,r)) return HUGE_VAL;
  while(l+1<r) {
    m=(l+r)/2;
    if(in_range(x,m,r)) l=m; else r=m;
  }
  /* use polynomial */
  return C->c[l][2]*2.+C->c[l][3]*x*6.;
#undef in_range
}/*}}}*/

double cspline_val(const struct cspline *C,double x)/*{{{*/
{
#define in_range(x,left,right) ((b[left]-x)*(x-b[right])>-DBL_EPSILON) 
  int m,l=0,r=C->n-1;
  const double *b=C->x;
  /* search interpolating interval */
  if(!in_range(x,l,r)) return HUGE_VAL;
  while(l+1<r) {
    m=(l+r)/2;
    if(in_range(x,m,r)) l=m; else r=m;
  }
  /* use polynomial */
  return C->c[l][0]+C->c[l][1]*x+C->c[l][2]*x*x+C->c[l][3]*x*x*x;
#undef in_range
}/*}}}*/

int cspline_init(struct cspline *C,double *xin,double *yin,int n)/*{{{*/
  /* input array must be sorted wrt x in either way */
{
#define nalloc(u) (u=malloc(sizeof(*u)*n))
  double *x,*y,*z,*h,*d,*b;
  double (*c)[4];
  int i;
  x=y=z=h=d=b=NULL;c=NULL;
  if(n<2) return -1;
  if(!(nalloc(x)&&nalloc(y)&&nalloc(z)&&nalloc(h)&&nalloc(d)&&nalloc(b)&&nalloc(c))) {
    free(x);free(y);free(z);free(h);free(b);free(d);free(c);
    return -1;
  }
  if(xin[0]<xin[n-1]) for(i=0;i<n;i++) { x[i]=xin[i]; y[i]=yin[i]; }
  else for(i=0;i<n;i++) { x[i]=xin[n-i-1]; y[i]=yin[n-i-1]; }
  /* building the tridiagonal system: i=1..n-2  */
  for(i=0,h[n-1]=0;i<n-1;i++) h[i]=x[i+1]-x[i]; /* subdiag */
  for(i=1;i<n-1;i++) { 
    d[i]=2.*(x[i+1]-x[i-1]);                  /* diagonal */
    b[i]=6.*((y[i+1]-y[i])/h[i]-(y[i]-y[i-1])/h[i-1]); /* right hand side */
  }
  /* Gauss elimination */
  for(i=2;i<n-1;i++) { d[i]-=h[i-1]*h[i-1]/d[i-1]; b[i]-=h[i-1]*b[i-1]/d[i-1]; }
  /* back-substitution */
  for(i=n-2,z[0]=z[n-1]=0;i>0;i--) z[i]=(b[i]-h[i]*z[i+1])/d[i];
  /* building the 3rd order polynom's coefficients */
  for(i=0;i<n-1;i++) {
    c[i][0]=(x[i+1]*y[i]-x[i]*y[i+1])/h[i]+h[i]/6.*(z[i+1]*x[i]-z[i]*x[i+1])
      +(z[i]*x[i+1]*x[i+1]*x[i+1]-z[i+1]*x[i]*x[i]*x[i])/(6.*h[i]);
    c[i][1]=(z[i+1]*x[i]*x[i]-z[i]*x[i+1]*x[i+1])/(2.*h[i])+
      (y[i+1]-y[i])/h[i]-h[i]*(z[i+1]-z[i])/6.;
    c[i][2]=(z[i]*x[i+1]-z[i+1]*x[i])/(2.*h[i]);
    c[i][3]=(z[i+1]-z[i])/(6.*h[i]);
  }
  C->c=c; C->x=x; C->n=n;
  free(y);free(z);free(h);free(b);free(d);
  return 0;
#undef nalloc
}/*}}}*/

int cspline_is_initialized(struct cspline *C)/*{{{*/
{
  return C->c!=NULL;
}/*}}}*/

void cspline_destroy(struct cspline *C)/*{{{*/
{
  free((void*)C->x);
  free(C->c); C->c=0;
  C->n=0;
}/*}}}*/

/* CSPLINE }}} */

/* jackknife {{{ */

int Njack=20;

static double *dalloc(size_t ndouble)
{
  double *x=malloc(sizeof(double)*ndouble);
  if(x==NULL) err(1,"Crashed when allocating %u doubles",(unsigned)ndouble);
  return x;
}

static double **dalloc2(size_t x,size_t y)
  /*   array up to [x-1][y-1] */
{
  double **ptr,*data;
  size_t i;
  ptr=malloc(sizeof(double)*x);
  if(ptr==NULL) err(1,"Crashed when allocating %u pointers",(unsigned)x);
  data=malloc(sizeof(double)*x*y);
  if(data==NULL) err(1,"Crashed when allocating %u doubles",(unsigned)(x*y));
  for(i=0;i<x;i++) ptr[i]=&data[i*y];
  return ptr;
}

static void dfree2(double **ptr)
{
  free(ptr[0]);
  free(ptr);
}

void jack_reset(double *J)
{
  int j;
  for(j=0;j<=Njack;j++) J[j]=0.;
}

double * jack_new()
{
  /* [0]: full sample, rest: jack-knife */
  double *J=dalloc(Njack+1);
  jack_reset(J);
  return J;
}

void jack_delete(double *J)
{
  free(J);
}

void jack_array_delete(double **JA)
{
  dfree2(JA);
}

double **jack_array_new(int n_observable)
{
  double **JA=dalloc2(n_observable,Njack+1);
  int i;
  for(i=0;i<n_observable;i++) jack_reset(JA[i]);
  return JA;
}

void jack_add(double *J,double data,int configuration_index,int nconfiguration)
{
  int j,js=((configuration_index*Njack)/nconfiguration)%Njack+1;
  for(j=0;j<=Njack;j++) if(j!=js) J[j]+=data;
}

void jack_div(double *R,const double *J,const double *N)
{
  int j;
  for(j=0;j<=Njack;j++) R[j]=J[j]/N[j];
}

double jack_error(double *J)
{
  int j;
  double devsq=0;
  for(j=1;j<=Njack;j++) devsq+=pow(J[j]-J[0],2.);
  return sqrt(devsq*(Njack-1)/Njack);
}

void jack_print(FILE *F,double *J)
{
  int j;
  fprintf(F,"%g %g",J[0],jack_error(J));
  for(j=1;j<=Njack;j++) fprintf(F," %g",J[j]);
}

/* jackknife }}} */

/* Linked list that accomodate one flow.
 * There is one entry per flow time. */

struct list_flow {
  double t;
  double et;
  double ex;
  int *nentry; /* shared integer object that knows the length of the list */
  struct list_flow *next_entry;
};

/* Linked list that accomodate one flow.
 * There is one entry per flow time. */

struct list_conf {
  struct list_flow *flow;
  int *nentry;/* shared integer object that knows the length of the list */
  struct list_conf *next_entry;
};

/* This points to our function of choice, that calculates relevant flow.
 * The use of the temporal, spatial or full wlow is implemented this way.
 * It can be flow_value_avg (default), flow_value_x or flow_value_t.
 */

double (*flow_value)(const struct list_flow *);

void *xmalloc(size_t s)/*{{{*/
{
  /* allocate-or-die function */
  void *t=malloc(s);
  if(!t) err(1,"malloc has failed for %lu bytes",(unsigned long)s);
  return t;
}/*}}}*/

struct list_flow *read_flow(FILE *F)/*{{{*/
{
  /* Reads in one flow data from the file.  There can be more
   * flow data concatenated in a single file. */
  /* The data is put into a linked list structure,
   * its head element is returned */
  char line[max_line_len];
  double t,et,ex;
  struct list_flow *first_entry=NULL,*this_entry=NULL;
  while(fgets(line,max_line_len,F)) {
    if(sscanf(line,Flow_line_format,&t,&et,&ex)==3) {
      if(first_entry==NULL)  {
	this_entry=first_entry=xmalloc(sizeof(*first_entry));
	first_entry->nentry=xmalloc(sizeof(int));
	first_entry->nentry[0]=0;
      } else {
	this_entry->next_entry=xmalloc(sizeof(*first_entry));
	this_entry->next_entry->nentry=this_entry->nentry;
	this_entry=this_entry->next_entry;
      }
      this_entry->t=t;
      this_entry->et=et;
      this_entry->ex=ex;
      this_entry->next_entry=NULL;
      this_entry->nentry[0]++;
    } else if(first_entry) break; 
    /* we have already read in a flow, here it ends */
  }
  /* last read non-flow line is lost. It is usually some footer line. */
  return first_entry;
}/*}}}*/

struct list_conf *read_conf(char *file_list[],int nfile)/*{{{*/
{
  /* this function loops over a list of files,
   * with one or more flow data in each. 
   * A linked list is prodeced, with one entry per flow.
   * The pointer to the head entry is returned. */
  struct list_conf *first_conf=NULL,*this_conf=NULL;
  struct list_flow *this_flow;
  int i;
  for(i=0;i<nfile;i++) {
    FILE *F;
    F=fopen(file_list[i],"r");
    if(!F) {
      warnx("I could not read the input file %s",file_list[i]);
      continue;
    }
    while((this_flow=read_flow(F))) {
      struct list_conf *new_conf=xmalloc(sizeof(*first_conf));
      if(first_conf==NULL) {
	this_conf=first_conf=new_conf;
	first_conf->nentry=xmalloc(sizeof(int));
	first_conf->nentry[0]=0;
      } else {
	this_conf->next_entry=new_conf;
	this_conf=new_conf;
	this_conf->nentry=first_conf->nentry;
      }
      this_conf->nentry[0]++;
      this_conf->flow=this_flow;
      this_conf->next_entry=NULL;
    }
    fclose(F);
  }
  return first_conf;
}/*}}}*/

int find_max_flow_length(const struct list_conf *L)/*{{{*/
{
  /* Flow lengths are not necessarily uniform in the ensemble.
   * This function finds the longest one and returns its length.  */
  int max=0;
  while(L) {
    if(max<L->flow->nentry[0]) max=L->flow->nentry[0];
    L=L->next_entry;
  }
  return max;
}/*}}}*/

int count_configs_with_flow_at_least_that_long(const struct list_conf *L,int min)/*{{{*/
{
  /* Flow lengths are not necessarily uniform in the ensemble.
   * This function finds the number of flows that have at least 'min'
   * entries */
  int n=0;
  while(L) {
    if(min<=L->flow->nentry[0]) n++;
    L=L->next_entry;
  }
  return n;
}/*}}}*/

int find_ideal_flow_length(const struct list_conf *L)/*{{{*/
{
  /* Flow lengths are not necessarily uniform in the ensemble. 
   * Since we take a derivative of the flow, it is necessary to
   * have the same configurations for all relevant 't' values.
   * This is a heuristic algorithm, where we drop the very short
   * flow files (that are likely to be results of a truncated run),
   * and keep t as big as possible, so that about 90% of the
   * configurations are in.
   * */
  int nall,nconf;
  int max=find_max_flow_length(L);
  int try=max;
  if(L==NULL) return 0;
  nall=L->nentry[0];
  do {
    max=try;
    nconf=count_configs_with_flow_at_least_that_long(L,max);
    try-=5;
  } while(try>0 && nconf<nall*0.9);
  return max;
}/*}}}*/

/* The following functions will be called through the flow_value pointer {{{ */

double flow_value_avg(const struct list_flow *F)/*{{{*/
{
  return F->t*F->t*(F->et+F->ex);
}/*}}}*/

double flow_value_t(const struct list_flow *F)/*{{{*/
{
  return F->t*F->t*2*F->et;
}/*}}}*/

double flow_value_x(const struct list_flow *F)/*{{{*/
{
  return F->t*F->t*2*F->ex;
}/*}}}*/

/* flow_value functions }}} */

struct cspline * spline_from_flow(const struct list_conf *L)/*{{{*/
{
  /* This function returns a pointer to the first element of an array
   * of (Njack+1) cspline objects.
   * The first one is an interpolation of the full sample, the rest
   * correspond to the a jack-knife sample */
  int nconf;
  int j,n,f;
  struct cspline *S;
  double *F_array;
  double **JF,**NF;
  Nline=find_ideal_flow_length(L);
  nconf=count_configs_with_flow_at_least_that_long(L,Nline);
  if(nconf==0) errx(1,"No configuration");
  F_array=dalloc(Nline); /* a local copy of the flow */
  JF=jack_array_new(Nline);
  NF=jack_array_new(Nline);
  T_array=dalloc(Nline); /* global time array */
  for(n=0;L;L=L->next_entry) if(Nline<=L->flow->nentry[0]) {
    struct list_flow *F=L->flow;
    for(f=0;f<Nline && F;F=F->next_entry,f++) {
      jack_add(JF[f],flow_value(F),n,nconf);  /* data */
      jack_add(NF[f],1.0,n,nconf);            /* counter */
      if(n==0) T_array[f]=F->t;
      else if(T_array[f]!=F->t)
	errx(1,"Mismatch in the flow time");
    }
    n++;
  }
  /* data normalized: average within the jack-knife sample*/
  /* we do this for every flow time here */
  for(f=0;f<Nline;f++) jack_div(JF[f],JF[f],NF[f]); 
  jack_array_delete(NF);
  T_max=T_array[Nline-1];
  S=xmalloc(sizeof(*S)*(Njack+1));
  for(j=0;j<=Njack;j++) {
    for(f=0;f<Nline;f++) F_array[f]=JF[f][j];
    if(cspline_init(&S[j],T_array,F_array,Nline))
      errx(1,"spline initialization has failed with %d long flows",Nline);
  }
  free(F_array);
  jack_array_delete(JF);
  return S;
}/*}}}*/

double solve_w0(const struct cspline *S,double cut,double lo,double hi)/*{{{*/
{
  /* a very simple equation solver */
  /* the result must be bracketed between lo and hi */
  /* the resulting t is returned */
  const double tol=1e-6;
  if(hi<lo) return HUGE_VAL;
  while(hi-lo>tol) {
    double mid=(lo+hi)/2.;
    double y=mid*cspline_derive(S,mid);
    if(y<cut) lo=mid; else hi=mid;
  }
  return (lo+hi)/2.;
}/*}}}*/

double get_the_scale(struct cspline *S,double cut)/*{{{*/
{
  double lo=0.5; /* below that the flow is very non-universal */
  double hi=T_max;
  double t,scale;
  t=solve_w0(S,cut,lo,hi);
  scale=sqrt(t);
  if(Opt_f) return Scale_in_fermi/scale;
  else return scale;
}/*}}}*/

void tell_the_scale(struct cspline *spline,double cut)/*{{{*/
{
  int j;
  double *scale=jack_new();
  for(j=0;j<=Njack;j++)
    scale[j]=get_the_scale(&spline[j],cut);
  if(jack_error(scale)==0.0) {
    if(!Opt_o[0])
      printf("Scale determination has failed. Check the flow using -o\n");
    else
      printf("Scale determination has failed. Check the flow.\n");
  } else {
    if(Opt_j) {
      jack_print(stdout,scale);
      putchar('\n');
    } else {
      printf("%g %g\n",scale[0],jack_error(scale));
    }
  }
  jack_delete(scale);
}/*}}}*/

double scale_in_fermi(double cut)/*{{{*/
{
  double s;
  if(cut==0.3) {
    s=0.1755;
  } else {
    errx(1,"I do not know the scale if the cut is not at 0.3");
  }
  return s;
}/*}}}*/

void write_flow(const char *name,struct cspline *spline)/*{{{*/
{
  /* The field strength and its derivatives are written out
   * in dimensionless combinations of derivatives and products by 't' */
  int l,j;
  double *flow=jack_new();
  double *dflow=jack_new();
  double *ddflow=jack_new();
  FILE *F=fopen(name,"w");
  if(!F) err(1,"Could not create the output file: %s",name);
  for(l=0;l<Nline;l++) {
    double t=T_array[l];
    for(j=0;j<=Njack;j++) {
      flow[j]=cspline_val(&spline[j],t);
      dflow[j]=t*cspline_derive(&spline[j],t);
      ddflow[j]=t*t*cspline_derive2(&spline[j],t);
    }
    fprintf(F,"%g %g %g %g %g %g %g\n",t,
	flow[0],jack_error(flow),
	dflow[0],jack_error(dflow),
	ddflow[0],jack_error(ddflow)
	);
  }
  fclose(F);
  jack_delete(flow);
  jack_delete(ddflow);
  jack_delete(dflow);
}/*}}}*/

void flow_format(const char *label)/*{{{*/
{
  /* This function initializes the parser of the flow files.
   * We simply set the format string that will be used
   * later in an sscanf call from read_flow()
   */
  snprintf(Flow_line_format,sizeof(Flow_line_format),
      "%s %%lf %%lf %%lf",label);
}/*}}}*/

void options(int argc,char **argv)/*{{{*/
{
  int o;
  flow_value=flow_value_avg;
  while((o=getopt(argc,argv,"hc:o:xtj:fs:"))!=-1) switch (o) {
    case 'h': help(); exit(0); break;
    case 'c': Cut_value=atof(optarg); break;
    case 'o': strncpy(Opt_o,optarg,sizeof(Opt_o)-1); break;
    case 'x': flow_value=flow_value_x; break;
    case 't': flow_value=flow_value_t; break;
    case 'j': Njack=atoi(optarg); Opt_j=1; break;
    case 'f': Opt_f=1; break;
    case 's': flow_format(optarg);break;
    default: puts("You can ask for help: -h"); 
	     exit(EXIT_FAILURE);
  }
}/*}}}*/

int main(int argc,char **argv)/*{{{*/
{
  struct list_conf *L;
  struct cspline *S;
  options(argc,argv);
  L=read_conf(argv+optind,argc-optind);
  S=spline_from_flow(L);
  if(Opt_f) Scale_in_fermi=scale_in_fermi(Cut_value);
  tell_the_scale(S,Cut_value);
  if(Opt_o[0]) write_flow(Opt_o,S);
  return 0;
}/*}}}*/
